"""Added response table

Revision ID: d5465d0080fc
Revises: e460b5aa75d4
Create Date: 2023-08-30 04:28:10.720539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5465d0080fc'
down_revision = 'e460b5aa75d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
