"""Added relationship between survey and response

Revision ID: e721f0f6ecb0
Revises: ba333aa1b947
Create Date: 2023-08-31 02:03:16.592918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e721f0f6ecb0'
down_revision = 'ba333aa1b947'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
